## Model configuration of microcircuit network
Model Name: Microcircuit_Small
Dataset Name: Microcircuit_Small
Definitions: !include_default Definitions.yaml
Global Parameters: !include_default Global.yaml
Geometry:
  # 80 neurons
  # 200 um electrode spacing
  # 30 um electrode size
  Parametric Surface:
    Origin:
      U: median
      V: median
      L: max
    Layer Extents:
      SO:  [[0.0,0.0,0.0], [1000.0,1000.0,100.0]] 
      SP:  [[0.0,0.0,100.0],[1000.0,1000.0,150.0]]
      SR:  [[0.0,0.0,150.0], [1000.0,1000.0,350.0]]
      SLM: [[0.0, 0.0,350.0], [1000.0, 1000.0, 450.0]]
    Rotation: [0.0, 0.0, 0.0]
  Cell Constraints:
    PC:
      SP: [100., 120.] # Lee, ..., Soltesz. Neuron 2014
    PVBC:
      SR: [150., 200.0] # Booker, Vida. Cell & Tissue Research 2018
  Cell Distribution:
    STIM:
      SO:  0
      SP:  10
      SR:  0
      SLM: 0
    PYR:
      SO:  0
      SP:  80
      SR:  0
      SLM: 0
    PVBC: #5530
      SO:  35
      SP:  10
      SR:  8
      SLM: 0
    OLM: #1640
      SO:  44
      SP:  0
      SR:  0
      SLM: 0
Random Seeds: !include_default Random.yaml
Connection Generator: !include_default Connections.yaml
Cell Data: MiV_Cells_Microcircuit_Small_20220410.h5
Connection Data: MiV_Connections_Microcircuit_Small_20220410.h5
Recording: !include_default Recording.yaml
Stimulus: !include_default Input_Configuration.yaml
Analysis: !include_default Analysis_Configuration.yaml
Cell Types:
  PYR:
    template: SC_nrn
    mechanism file: PYR_SoldadoMagraner.yaml
    synapses:
      density: !include_default PYR_synapse_density.yaml
  OLM:
    template: OLMCell
    synapses:
      density: !include_default OLM_synapse_density.yaml
  PVBC:
    template: PVBasketCell
    synapses:
      density: !include_default PVBC_synapse_density.yaml
  STIM:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train